if __name__ == "__main__":
    from datetime import datetime as dt

    README_PATH = "README.md"
    README_GEN_PATH = README_PATH + ".build"

    with open(README_GEN_PATH, "r") as f:
        readme = {"content": f.read()}

        def put(var, text):
            readme["content"] = readme["content"].replace("{{" + var + "}}", text)

        put("DATE", str(dt.now()))
        put("AUTHOR", "[Ethan Uppal](https://www.ethanuppal.com)")

        with open(README_PATH, "w") as f:
            f.write(
                "<!-- THIS FILE IS GENERATED AUTOMATICALLY. -->\n<!-- DO NOT EDIT THIS FILE. -->\n<!-- EDIT README.md.build INSTEAD. -->\n"
                + readme["content"]
            )
